source 'https://github.com/CocoaPods/Specs.git'
workspace 'CarnivalStreamExamples.xcworkspace'
xcodeproj 'CarnivalSwiftStreamExamples/CarnivalSwiftStreamExamples.xcodeproj'
xcodeproj 'CarnivalStreamExamples/CarnivalStreamExamples.xcodeproj'

target :CarnivalSwiftStreamExamples do
    platform :ios, "8.0"
    pod "Carnival"
    pod "SDWebImage"
    pod "DateTools"
    xcodeproj 'CarnivalSwiftStreamExamples/CarnivalSwiftStreamExamples.xcodeproj'
end

target :CarnivalStreamExamples do
    platform :ios, "8.0"
    pod "Carnival"
    pod "SDWebImage"
    pod "DateTools"
    xcodeproj 'CarnivalStreamExamples/CarnivalStreamExamples.xcodeproj'
end
