source 'https://github.com/CocoaPods/Specs.git'
workspace 'MarigoldStreamExamples.xcworkspace'
xcodeproj 'MarigoldSwiftStreamExamples/MarigoldSwiftStreamExamples.xcodeproj'
xcodeproj 'MarigoldStreamExamples/MarigoldStreamExamples.xcodeproj'

target :MarigoldSwiftStreamExamples do
    platform :ios, "12.0"
    pod "Marigold"
    pod "SDWebImage"
    pod "DateTools"
    xcodeproj 'MarigoldSwiftStreamExamples/MarigoldSwiftStreamExamples.xcodeproj'
end

target :MarigoldStreamExamples do
    platform :ios, "12.0"
    pod "Marigold"
    pod "SDWebImage"
    pod "DateTools"
    xcodeproj 'MarigoldStreamExamples/MarigoldStreamExamples.xcodeproj'
end
